name: INSuRE_Malware_Artribution
channels:
  - anaconda
dependencies:
  - python=3.6   # or 2.7
  - pandas=0.24.2
  - numpy=1.16.*
  - scikit-learn=0.20.*
  - pip:
    - google-api-python-client
    - google-auth-httplib2
    - google-auth-oauthlib
